# Generated by Django 4.1.7 on 2023-05-31 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('stock', models.IntegerField(default=0)),
                ('image', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'producto',
            },
        ),
    ]
