# Generated by Django 4.1.7 on 2023-05-31 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0002_producto_descripcion_producto_precio_carrito'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carrito',
            name='producto_id_producto',
            field=models.ForeignKey(db_column='producto_id_producto', on_delete=django.db.models.deletion.CASCADE, to='mynakama.producto'),
        ),
    ]
