# Generated by Django 4.1.7 on 2023-05-31 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0003_alter_carrito_producto_id_producto'),
    ]

    operations = [
        migrations.CreateModel(
            name='Figura',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mynakama.producto')),
                ('material', models.CharField(max_length=100)),
            ],
            bases=('mynakama.producto',),
        ),
        migrations.CreateModel(
            name='Manga',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mynakama.producto')),
                ('editorial', models.CharField(max_length=100)),
            ],
            bases=('mynakama.producto',),
        ),
        migrations.CreateModel(
            name='Peluche',
            fields=[
                ('producto_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mynakama.producto')),
                ('material', models.CharField(max_length=100)),
            ],
            bases=('mynakama.producto',),
        ),
    ]
