# Generated by Django 4.1.7 on 2023-05-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0005_manga_tomo_alter_figura_table_alter_manga_table_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manga',
            name='tomo',
        ),
    ]
