# Generated by Django 4.1.7 on 2023-05-31 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0006_remove_manga_tomo'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='fabricante',
            field=models.CharField(default='Sin fabricante', max_length=100),
        ),
        migrations.AddField(
            model_name='figura',
            name='medidas',
            field=models.CharField(default=0, max_length=100),
        ),
        migrations.AddField(
            model_name='manga',
            name='autor',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='manga',
            name='tomo',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='manga',
            name='editorial',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterModelTable(
            name='figura',
            table='figura',
        ),
        migrations.AlterModelTable(
            name='manga',
            table='manga',
        ),
    ]
