# Generated by Django 4.1.7 on 2023-05-31 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0008_remove_producto_image_producto_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='figura',
            name='personaje',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
