# Generated by Django 4.1.7 on 2023-06-05 21:48

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0010_remove_carrito_auth_user_id_alter_producto_image1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='producto', editable=False, populate_from='nombre_producto'),
        ),
    ]
