# Generated by Django 4.1.7 on 2023-06-06 05:32

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0011_producto_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Anime',
            fields=[
                ('id_anime', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'anime',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='producto',
            name='slug',
            field=autoslug.fields.AutoSlugField(editable=False, populate_from='nombre_producto'),
        ),
        migrations.AddField(
            model_name='producto',
            name='anime_id_anime',
            field=models.ForeignKey(db_column='anime_id_anime', default=1000, on_delete=django.db.models.deletion.CASCADE, to='mynakama.anime'),
        ),
    ]
