# Generated by Django 4.1.7 on 2023-06-21 04:21

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0014_producto_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='-', editable=False, populate_from='nombre'),
        ),
    ]
