# Generated by Django 4.1.7 on 2023-07-03 02:04

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mynakama', '0015_anime_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text1', models.TextField(null=True)),
                ('text2', models.TextField(null=True)),
                ('text3', models.TextField(null=True)),
                ('text4', models.TextField(null=True)),
                ('image1', models.CharField(default='-', max_length=200)),
                ('nombre_tienda', models.CharField(default='-', max_length=200)),
                ('direccion', models.CharField(default='-', max_length=200)),
                ('image2', models.CharField(default='-', max_length=200)),
                ('telefono', models.CharField(default='-', max_length=200)),
            ],
            options={
                'db_table': 'empresa',
            },
        ),
        migrations.AlterField(
            model_name='anime',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='', editable=False, populate_from='nombre'),
        ),
    ]
